### ISSUE TITLE
`Base.show(::IO, ::T)` does not return parseable Julia code for numerous types

### ISSUE THREAD

**Issue by brainandforce** [PainterQubits/Unitful.jl#743] opened 2024-10-17 22:03 UTC
[From the docstring of `Base.show`:](https://docs.julialang.org/en/v1/base/io-network/#Base.show-Tuple{IO,%20Any})

> The representation used by `show` generally includes Julia-specific formatting and type information, and should be parseable Julia code when possible.

Calling `show` on units or unitful values provided by this package does not provide parseable Julia code for the value:
```julia-repl
julia> show(stdout, u"km/s")
km s^-1

julia> show(stdout, 4u"km/s")
4 km s^-1
```
I'd expect something along the lines of 
```julia-repl
julia> show(stdout, u"km/s")
u"km * s^-1"

julia> show(stdout, 4u"km/s")
4u"km * s^-1"
```
Fixing this should not affect the pretty printing methods, which use `show(::IO, ::MIME"text/plain", ::T)`.

**Comment by giordano** [comment] 2024-10-17 22:06
Duplicate of #412

**Closed by giordano** 2024-10-17 22:06 UTC
