### ISSUE TITLE
Incorrect conversion from Hz to rad/s

### ISSUE THREAD

**Issue by jonniediegelman** [PainterQubits/Unitful.jl#637] opened 2023-03-27 13:47 UTC
```julia
julia> uconvert(u"rad/s", 1.0u"Hz")
1.0 rad s⁻¹
```
I would expect this to be `6.2831853 rad  s⁻¹`

**Comment by giordano** [comment] 2023-03-27 15:54
I thought I had posted a comment, but it looks like it got lost.  This has also nothing to do with Hz or seconds:
```
julia> uconvert(u"rad", 1.0)
1.0 rad
```

**Comment by giordano** [comment] 2023-03-29 20:31
Closing as duplicate of #636 (which is where I had posted my comment)

**Closed by giordano** 2023-03-29 20:31 UTC
