### ISSUE TITLE
Occasional seg faults on 0.7/1.0

### ISSUE THREAD

**Issue by nicoleepp** [PainterQubits/Unitful.jl#193] opened 2018-11-16 22:46 UTC
Seg fault when `using ExtensionPkg` before `using Unitful` in another module:

This came up here https://github.com/lanl-ansi/PowerModelsAnnex.jl/issues/29 and was resolved for that package specifically (turning precompilation off for the package that extends Unitful solves the error).

But I noticed that if that package did a `using UnitfulUS` before `using Unitful` it would also cause seg faults when loading `using PowerModelsAnnex`. Not sure the cause exactly but I suspect it might be related to Unitful itself/precompilation in general as this appears not to be specific to that extension of Unitful.

**Comment by cstjean** [comment] 2018-11-16 23:44
I've had a ridiculous amount of segfaults since I started using Unitful. I don't think there's anything that  can be done about it, besides filing reports with minimal code examples to julialang, unfortunately. Eg. https://github.com/JuliaLang/julia/issues/29936 came from Unitful, and sounds very similar.

**Comment by nicoleepp** [comment] 2018-11-19 21:38
Even with precompilation disabled, using Unitful on 0.7/1.0 will occasionally result in seg faults.

**Comment by ajkeller34** [comment] 2018-11-19 21:44
I'd like to offer help, but usually segfaults are a Julia problem, unless it turns out I'm doing something unsafe in Unitful. I can audit my use of unsafe macros like `@inbounds`, etc. but to be honest I haven't had any segfaults. I also don't use separate unit packages that often, so maybe that points to the source of the problem?

**Comment by ajkeller34** [comment] 2019-06-17 04:07
I'd be curious to know if the segfault situation has improved after merging https://github.com/PainterQubits/Unitful.jl/pull/243. I don't have evidence to claim the issues are related although there were some unsafe uses of generated functions prior to that PR.

**Comment by cstjean** [comment] 2019-06-17 13:15
FWIW I haven't had segfaults in a long time...

**Comment by omus** [comment] 2019-06-17 14:15
We've still been seeing segfaults on our private CI. I'll set it up to make use of the `master` branch for now and report back.

**Comment by omus** [comment] 2019-06-24 19:56
Yesterday we saw a segfault on the CI using the Unitful `master` branch. We were also using the [PowerSystemsUnits.jl](https://github.com/invenia/PowerSystemsUnits.jl) which was using [v0.1.0](https://github.com/invenia/PowerSystemsUnits.jl/releases) which may have been the cause of the segfault. We'll try to confirm this by using the v0.2.0 release.

**Comment by omus** [comment] 2019-07-02 19:40
We haven't seen any segfaults with updated version of PowerSystemsUnits.jl. I think it's safe to close this issue. We can re-open if they appear again.

**Closed** 2019-07-02 22:08 UTC
