### ISSUE TITLE
making units for things I want to count

### ISSUE THREAD

**Issue by drdozer** [PainterQubits/Unitful.jl#473] opened 2021-08-04 11:23 UTC
I often want to do unit-safe arithmetic on things that aren't si units. For example, I want a unit for books and for bookshelfs. Then I can express the capacity of a bookshelf with the units books/bookshelf. However, I can't see an easy way to do this kind of ad-hockery. The `@uinit` macro doesn't seem appropriate as it wants a conversion factor to something else. The `@dimension` macro also doesn't seem to really fit, since I'm not sure how I should express books or bookshelfs as dimensions.

Any help would be greatly appreciated. I would love to make my arithmetic unitful as a matter of course, for the domain-specific quantities I have that day.

**Comment by giordano** [comment] 2021-08-04 11:41
Duplicate of #306?

**Closed** 2021-08-05 05:07 UTC
