### ISSUE TITLE
numeric type not preserved in uconvert

### ISSUE THREAD

**Issue by islent** [PainterQubits/Unitful.jl#502] opened 2021-11-29 15:20 UTC
MWE: `Float32` is converted to `Float64`
```jl
julia> using Unitful

julia> a = 1.0f0u"km/yr"
1.0f0 km yr^-1

julia> b = uconvert(u"m/s", a)
3.1688087f-5 m s^-1
```
whenever the unit conversion has some algebraic calculation. For example, `basefact` of `yr` dividing `s` gives `Float64`, and as a result, `Float32` is shifted to `Float64`.

https://github.com/PainterQubits/Unitful.jl/blob/955fc05fe049a12c15b1372a16eb7d8685a8bd50/src/conversion.jl#L18-L22

**Comment by cstjean** [comment] 2021-11-29 20:02
FYI, type-stable refers to the output type being inferrable by the compiler from input types, your other title "numeric type not preserved in uconvert" is more accurate...

**Comment by sostock** [comment] 2021-11-30 10:57
Duplicate of #190.

**Closed by sostock** 2021-11-30 10:57 UTC
