### ISSUE TITLE
Roundtrip printing

### ISSUE THREAD

**Issue by YingboMa** [PainterQubits/Unitful.jl#466] opened 2021-07-16 21:56 UTC
Currently, `show` displays units that are cannot be copy-pasted into Julia REPL. This makes serializing expressions impossible if the expression contains unitful objects.
```julia
julia> using Unitful

julia> unit = u"m/s";

julia> show(unit)
m s⁻¹
julia> :(x = $unit)
:(x = m s⁻¹)
```
In Julia, by convention, pretty print should only be done on MIME methods, and default `show` should do roundtrip

**Comment by giordano** [comment] 2021-07-16 22:00
> In Julia, by convention, pretty print should only be done on MIME methods, and default show should do roundtrip

Really?  I thought that was `repr` (not that the result here is different)

**Comment by giordano** [comment] 2021-07-16 22:08
Duplicate of #391

**Closed by giordano** 2021-07-16 22:08 UTC
