### ISSUE TITLE
determinant of simple Unitful matrix fails

### ISSUE THREAD

**Issue by JeffFessler** [PainterQubits/Unitful.jl#453] opened 2021-05-31 20:55 UTC
MWE:

```julia
using Unitful
using LinearAlgebra: det
A = [1u"m" 0u"m"; 0u"m" 1u"m"]
det(A)

2×2 Matrix{Quantity{Int64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}:
 1 m  0 m
 0 m  1 m

ERROR: LoadError: DimensionError: m and 1 m² are not dimensionally compatible.
Stacktrace:
 [1] convert(#unused#::Type{Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}, x::Quantity{Int64, 𝐋², Unitful.FreeUnits{(m²,), 𝐋², nothing}})
   @ Unitful ~/.julia/packages/Unitful/PcVKX/src/conversion.jl:112
 [2] det(A::Matrix{Quantity{Int64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}})
   @ LinearAlgebra /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/generic.jl:1558
 [3] top-level scope
   @ ~/src/julia/bug/unitful-det1.jl:4
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [5] top-level scope
   @ REPL[1]:1
```

This is not a very urgent for me but it arose when trying to diagnose Unitful matrix inverse failure that I will submit separately.

**Comment by JeffFessler** [comment] 2021-05-31 21:00
Here is a more interesting example for which a determinant is certainly well defined that also fails.

```julia
using Unitful
using LinearAlgebra: det
B = [1u"m^2" 0u"m"; 0u"m" 1]

2×2 Matrix{Quantity{Int64, D, U} where {D, U}}:
 1 m²  0 m
  0 m    1

det(B)

(similar error)
```

**Comment by giordano** [comment] 2021-05-31 21:09
Duplicate of #46

**Closed by giordano** 2021-05-31 21:09 UTC

**Comment by JeffFessler** [comment] 2021-06-01 01:45
Sorry for the duplicate issue.  I did a search for "determinant" under "issues" here and nothing showed up.

It need not exactly be a duplicate though.  Certainly if a general linear algebra solution were found then `det` would likely be solved too, but I believe it may be possible to address `det` relatively simply (albeit allocating) and I may be willing to make a PR if there is openness to it.  But if the preference here is to wait for a full linear algebra solution then I'll wait and continue to go "unitless" in the meantime.
